### ISSUE TITLE
Terminator OSX Download binary/installation instructions missing

### ISSUE THREAD

**Issue by checketts** [software-jessies-org/jessies#21]
I'm sorry if I overlooked the directions or file, but I can't seem to find the OSX precompiled binary. Am I looking in the wrong place or does one not exist?

If not are there simple build instructions?

**Comment by martindorey** [comment]
If you're after Terminator, the newest OS X "installer" we have is from slightly over a year ago, at https://drive.google.com/open?id=0BzZNCgKvEkQYbWlabGxZWWxJbjQ.  To my surprise, we do have build instructions at https://github.com/software-jessies-org/jessies/wiki/SalmaHayek but they predate the move to GitHub.

**Comment by checketts** [comment]
Thanks for the link to the OSX installer!
