### ISSUE TITLE
Terminator won't open even with java 11

### ISSUE THREAD

**Issue by LadyAleena** [software-jessies-org/jessies#30]
I have org.jessies.terminator 27.9.6921 on Debian Buster. I get the following error message. How do I fix it, or is there another version I can try?

![screenshot_jessie_java_erro](https://user-images.githubusercontent.com/123256/60849037-fe0e9880-a1b6-11e9-80eb-1c28c75d2886.png)

**Comment by martindorey** [comment]
Wow, where did you find a version that old?  The latest version is 28.203.7371 from 2019-06-13, which does support Java 11.  Hmm, looks like it came from https://code.google.com/archive/p/jessies/downloads.  I guess I'll remove the link to that from the Downloads page.  It's the link to Google Drive that you want.

**Comment by LadyAleena** [comment]
I didn't get back here soon enough to cancel this. The upgrade fixed the problem. Again, sorry that I didn't get back here sooner. I just upgraded my Debian and am still cleaning up a few things.
