### ISSUE TITLE
Please add latest version to READMEs and wiki?

### ISSUE THREAD

**Issue by LadyAleena** [software-jessies-org/jessies#34]
Would you please add the latest versions of the software here to the README files and the wiki so I can tell at a glance if I should upgrade or not?

**Comment by martindorey** [comment]
New builds get uploaded to https://drive.google.com/drive/u/0/folders/1_6aBsmCOabtka5akRjo87v2JP1ST7FIU whenever there's a new git push during the previous day.  Most of the rare git pushes these days aren't interesting, but the builds are automated.  The way to tell would be to look at https://github.com/software-jessies-org/jessies/commits/master.  Maybe github could be persuaded to notify you, like it told me about this new issue.
