### ISSUE TITLE
Link fix in Wiki

### ISSUE THREAD

**Issue by hoijui** [software-jessies-org/jessies#35]
On the bottom of this wiki page:
https://github.com/software-jessies-org/jessies/wiki/Evergreen

there is a link to:

`https://github.com/software-jessies-org/jessies/wiki/SalmaHayek.md`

which should have the extension removed:

`https://github.com/software-jessies-org/jessies/wiki/SalmaHayek`

PS: I found out, that apparently there is no way to suggest a change on a github wiki where you don't have write access to, except.. the way I am doing right here. No web interface, and no pull-requests.
... really?

it is possible however, to [make the wiki publicly writeable](https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis).

**Comment by martindorey** [comment]
I made the change you suggested and indeed it works better.  I’m sure we could work out how to give you write access if you’ve got other such fixes.  Thanks!

**Comment by hoijui** [comment]
thanks :-)
