### ISSUE TITLE
Link to mailing list is 404

### ISSUE THREAD

**Issue by LadyAleena** [software-jessies-org/jessies#38]
The [link](https://github.com/software-jessies-org/jessies/blob/master/terminator/terminator-users@googlegroups.com) to the mailing list in the [Jessie terminator readme](https://github.com/software-jessies-org/jessies/blob/master/terminator/README.md) is 404.

**Comment by martindorey** [comment]
Whur, I didn't intentionally ask github to close it for me.  I at least wanted to say "Thanks for the report".

**Comment by LadyAleena** [comment]
That's okay @martindorey, the issue is fixed, so closing it is a good thing.
