### ISSUE TITLE
Tab titles do not update

### ISSUE THREAD

**Issue by ShadowAce** [software-jessies-org/jessies#48]
When I used Terminator under Fedora and ssh'ed into another server, the tab title would indicate the name of the server I was connected to.  Once I logged out of that server, the tab title would revert back to my directory name.

Now, under Pop!_OS 21_04, the tab titles do not revert back to the directory name.  When I have multiple tabs open, it can get confusing as to which tabs are actually connected to a server.  

Can this be corrected?

**Comment by martindorey** [comment]
While it's the terminal that displays the title, it's just doing what it's told, likely by the shell variable PS1 or PROMPT_COMMAND, as explained by https://github.com/software-jessies-org/jessies/wiki/TerminatorFAQ#how-can-i-set-the-windowtab-title-from-the-shell (or many other fine sources like https://askubuntu.com/a/252233/148633).  Perhaps one distro had set this for you and the other hadn't.

**Comment by ShadowAce** [comment]
Thank you!  Your last sentence (Perhaps one distro had set this for you and the other hadn't.) was the key for me to track it down.  Pop!_OS has the PROMPT_COMMAND setting commented out.  Once I enabled it, it works just like I want.
