### ISSUE TITLE
Change separator color

### ISSUE THREAD

**Issue by dshibanov** [software-jessies-org/jessies#50]
![image](https://user-images.githubusercontent.com/5215047/141646178-bd381a52-7fe6-4ded-b525-60a68b97110e.png)

Can anybody explain to me how to change separator color?

**Comment by martindorey** [comment]
https://github.com/software-jessies-org/jessies/wiki/TerminatorFAQ#this-is-not-gnome-terminator

**Comment by dshibanov** [comment]
oh.. sorry. thank you
